/**
 * iMessage adapter through Photon Spectrum (photon.codes). Photon owns the iMessage lines — no Mac
 * relay, no webhook: the `spectrum-ts` SDK holds an outbound gRPC stream both ways. The free tier
 * uses a shared line pool (up to 10 registered users, SMS/RCS fallback included); a shared line
 * can only reply to numbers that texted it first, which suits a personal assistant.
 *
 * `spectrum-ts` is large (gRPC, OpenTelemetry) and ESM-only, so it is not a Lattice dependency:
 * `lattice channels setup imessage` installs a pinned copy into `<dataDir>/channels/photon-sdk`
 * with a tiny ESM shim, and this adapter imports that shim at runtime.
 */
import { execFile } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { ChannelAdapter, ChannelStatus, InboundAttachment, InboundMessage, Logger } from '../types'

export const SPECTRUM_VERSION = '12.7.0'
const SHIM = 'photon-shim.mjs'
const MAX_INLINE_BYTES = 20 * 1024 * 1024

// The slice of the spectrum-ts surface this adapter uses, typed locally (the SDK is not a build dep).
interface SpectrumContent {
  type: string
  text?: string
  name?: string
  mimeType?: string
  size?: number
  items?: SpectrumMessage[]
  read?: () => Promise<Buffer>
}

interface SpectrumSpace {
  readonly id: string
  send(content: unknown): Promise<unknown>
  getMessage(id: string): Promise<SpectrumMessage | undefined>
}

interface SpectrumMessage {
  readonly id: string
  content: SpectrumContent
  direction: 'inbound' | 'outbound'
  sender: { id: string } | undefined
  space: SpectrumSpace
  timestamp: Date
  read(): Promise<void>
  react(reaction: string): Promise<unknown>
}

interface SpectrumApp {
  readonly messages: AsyncIterable<[SpectrumSpace, SpectrumMessage]>
  stop(): Promise<void>
}

interface SpectrumModule {
  Spectrum(options: { projectId: string; projectSecret: string; providers: unknown[]; options?: Record<string, unknown> }): Promise<SpectrumApp>
  text(source: string): unknown
  typing(state?: 'start' | 'stop'): unknown
  imessage: ((app: SpectrumApp) => { space: { get(id: string): Promise<SpectrumSpace>; create(handle: string): Promise<SpectrumSpace> } }) & { config(): unknown }
}

export interface PhotonAdapterOptions {
  projectId: string
  projectSecret: string
  sdkDir: string
  mediaDir: string
  log: Logger
  /** Injected in tests; production loads the installed SDK. */
  loadModule?: () => Promise<SpectrumModule>
  /** Whether attachments from this sender may be fetched (see TelegramAdapterOptions.mayDownload). */
  mayDownload?: (senderId: string) => boolean
}

export function photonSdkInstalled(sdkDir: string): boolean {
  return existsSync(join(sdkDir, SHIM)) && existsSync(join(sdkDir, 'node_modules', 'spectrum-ts', 'package.json'))
}

/** Install the pinned SDK and the shim. Runs npm, so it needs network access once. */
export async function installPhotonSdk(sdkDir: string, log: Logger): Promise<void> {
  mkdirSync(sdkDir, { recursive: true })
  writeFileSync(join(sdkDir, 'package.json'), `${JSON.stringify({ name: 'lattice-photon-sdk', private: true, type: 'module', dependencies: { 'spectrum-ts': SPECTRUM_VERSION } }, null, 2)}\n`)
  writeFileSync(
    join(sdkDir, SHIM),
    [
      '// Generated by `lattice channels setup imessage`: re-exports the pinned spectrum-ts surface.',
      "export { Spectrum, text, typing } from 'spectrum-ts'",
      "export { imessage } from 'spectrum-ts/providers/imessage'",
      ''
    ].join('\n')
  )
  log(`installing spectrum-ts@${SPECTRUM_VERSION} into ${sdkDir} …`)
  await new Promise<void>((resolve, reject) => {
    execFile('npm', ['install', '--no-audit', '--no-fund', '--omit=dev'], { cwd: sdkDir, maxBuffer: 16 * 1024 * 1024 }, (error, _stdout, stderr) => {
      if (error) reject(new Error(`npm install failed: ${stderr.trim().split('\n').slice(-3).join(' ') || error.message}`))
      else resolve()
    })
  })
}

// `import()` must survive the CJS bundle as a real dynamic import; esbuild would turn a literal one
// into require(), which cannot load an ESM-only package.
const dynamicImport = new Function('specifier', 'return import(specifier)') as (specifier: string) => Promise<unknown>

function kindForMime(mime: string): InboundAttachment['kind'] {
  if (mime.startsWith('image/')) return 'image'
  if (mime.startsWith('audio/')) return 'audio'
  return 'file'
}

export class PhotonAdapter implements ChannelAdapter {
  readonly id = 'imessage' as const
  readonly maxMessageChars = 2000
  readonly format = 'plain' as const

  private sdk: SpectrumModule | null = null
  private app: SpectrumApp | null = null
  private running = false
  private connected = false
  private lastError?: string
  private readonly spaces = new Map<string, SpectrumSpace>()
  private readonly recent = new Map<string, SpectrumMessage>()

  constructor(private readonly options: PhotonAdapterOptions) {}

  async start(sink: (message: InboundMessage) => void): Promise<void> {
    const load = this.options.loadModule ?? (async () => {
      if (!photonSdkInstalled(this.options.sdkDir)) throw new Error('the Photon SDK is not installed; run `lattice channels setup imessage`')
      return (await dynamicImport(pathToFileURL(join(this.options.sdkDir, SHIM)).href)) as SpectrumModule
    })
    this.sdk = await load()
    this.app = await this.sdk.Spectrum({
      projectId: this.options.projectId,
      projectSecret: this.options.projectSecret,
      providers: [this.sdk.imessage.config()],
      options: { flattenGroups: true }
    })
    this.running = true
    this.connected = true
    this.options.log('imessage: connected to Photon Spectrum')
    void this.consume(sink)
  }

  /** The SDK reconnects gRPC internally, but if its iterator ends or throws we re-subscribe. */
  private async consume(sink: (message: InboundMessage) => void): Promise<void> {
    let backoff = 1_000
    while (this.running && this.app) {
      try {
        for await (const [space, message] of this.app.messages) {
          if (!this.running) return
          this.connected = true
          this.lastError = undefined
          backoff = 1_000
          if (message.direction !== 'inbound') continue
          this.spaces.set(space.id, space)
          this.remember(message)
          const inbound = await this.normalize(space, message)
          if (!inbound) continue
          sink(inbound)
          // Mark read once the gateway has the message, so the owner sees "Read" right away.
          void message.read().catch(() => undefined)
        }
        if (this.running) this.options.log('imessage: inbound stream ended; re-subscribing')
      } catch (error) {
        if (!this.running) return
        this.connected = false
        this.lastError = (error as Error).message
        this.options.log(`imessage: inbound stream failed (${this.lastError}); retrying in ${backoff / 1000}s`)
      }
      await new Promise((resolve) => setTimeout(resolve, backoff))
      backoff = Math.min(backoff * 2, 30_000)
    }
  }

  private remember(message: SpectrumMessage): void {
    this.recent.set(message.id, message)
    if (this.recent.size > 200) this.recent.delete(this.recent.keys().next().value!)
  }

  private async normalize(space: SpectrumSpace, message: SpectrumMessage): Promise<InboundMessage | undefined> {
    const senderId = message.sender?.id
    if (!senderId) return undefined
    const texts: string[] = []
    const attachments: InboundAttachment[] = []
    const allowed = this.options.mayDownload?.(senderId) ?? true
    const visit = async (content: SpectrumContent): Promise<void> => {
      if (content.type === 'text' && content.text) texts.push(content.text)
      else if (content.type === 'group' && content.items) for (const item of content.items) await visit(item.content)
      else if ((content.type === 'attachment' || content.type === 'voice') && content.read && allowed) {
        const mime = content.mimeType ?? 'application/octet-stream'
        const name = content.name ?? `${content.type}-${message.id}`
        if (content.size && content.size > MAX_INLINE_BYTES) {
          texts.push(`(iMessage attachment ${name} is too large to fetch)`)
          return
        }
        try {
          const bytes = await content.read()
          mkdirSync(this.options.mediaDir, { recursive: true, mode: 0o700 })
          const path = join(this.options.mediaDir, `imessage-${Date.now()}-${name.replace(/[^\w.\- ]+/g, '_')}`)
          writeFileSync(path, bytes, { mode: 0o600 })
          attachments.push({ path, name, mime, kind: content.type === 'voice' ? 'audio' : kindForMime(mime) })
        } catch (error) {
          texts.push(`(could not fetch iMessage attachment ${name}: ${(error as Error).message})`)
        }
      }
      // Reactions, read receipts, typing and edits carry nothing for the assistant.
    }
    await visit(message.content)
    if (texts.length === 0 && attachments.length === 0) return undefined
    return {
      channel: 'imessage',
      conversationId: space.id,
      senderId,
      messageId: message.id,
      text: texts.join('\n'),
      attachments,
      receivedAt: message.timestamp instanceof Date ? message.timestamp.getTime() : Date.now()
    }
  }

  private async space(conversationId: string): Promise<SpectrumSpace> {
    const known = this.spaces.get(conversationId)
    if (known) return known
    if (!this.sdk || !this.app) throw new Error('iMessage is not connected')
    const im = this.sdk.imessage(this.app)
    // A bare E.164 number or email addresses a DM; anything else is a persisted space id.
    const space = /^\+?\d{7,15}$|@/.test(conversationId) ? await im.space.create(conversationId) : await im.space.get(conversationId)
    this.spaces.set(conversationId, space)
    return space
  }

  async stop(): Promise<void> {
    this.running = false
    this.connected = false
    await this.app?.stop().catch(() => undefined)
    this.app = null
  }

  async send(conversationId: string, text: string): Promise<void> {
    if (!this.sdk) throw new Error('iMessage is not connected')
    const space = await this.space(conversationId)
    try {
      await space.send(this.sdk.text(text))
    } catch (error) {
      if (/target not allowed/i.test((error as Error).message)) {
        throw new Error('Photon shared lines can only reply to numbers that texted the line first')
      }
      throw error
    }
  }

  async typing(conversationId: string, on: boolean): Promise<void> {
    if (!this.sdk) return
    const space = await this.space(conversationId)
    await space.send(this.sdk.typing(on ? 'start' : 'stop'))
  }

  async react(conversationId: string, messageId: string, emoji: string): Promise<void> {
    const message = this.recent.get(messageId) ?? (await (await this.space(conversationId)).getMessage(messageId))
    await message?.react(emoji)
  }

  status(): ChannelStatus {
    return { connected: this.connected, identity: 'Photon shared iMessage line', lastError: this.lastError }
  }
}
